pull_request_rules:
  - name: remove hold when CI passed
    conditions:
      - label=ci-passed
    actions:
      label:
        remove:
          - do-not-merge/hold
  - name: add hold when CI not passed
    conditions:
      - label!=ci-passed
    actions:
      label:
        add:
          - do-not-merge/hold
  - name: remove ci-pass when CI not passed
    conditions:
      - or:
        - check-success!=check
        - check-success!=Code Check (ubuntu18.04)
        - check-success!=Unit Test (ubuntu18.04)
        - check-success!=System Integration Test (ubuntu18.04)
        - check-success!=System Integration Test for Mixture (ubuntu18.04)
        - check-success!=System Integration Test for Upgrade (ubuntu18.04)
        - check-success!=System Integration Test for New Feature (ubuntu18.04)
        - check-success!=System Integration Test for Milvus Upgrade (ubuntu18.04)
        - check-success!=Test Deploy by Manifest (ubuntu18.04)
        - check-success!=codecov/patch
        - check-success!=codecov/project
    actions:
      label:
        remove:
          - ci-passed
  - name: add ci-pass when CI passed
    conditions:
      - check-success=check
      - check-success=Code Check (ubuntu18.04)
      - check-success=Unit Test (ubuntu18.04)
      - check-success=System Integration Test (ubuntu18.04)
      - check-success=System Integration Test for Mixture (ubuntu18.04)
      - check-success=System Integration Test for Upgrade (ubuntu18.04)
      - check-success=System Integration Test for New Feature (ubuntu18.04)
      - check-success=System Integration Test for Milvus Upgrade (ubuntu18.04)
      - check-success=Test Deploy by Manifest (ubuntu18.04)
      - check-success=codecov/patch
      - check-success=codecov/project
    actions:
      label:
        add:
          - ci-passed
