pull_request_rules:
  - name: Automatic merge on approval a
    conditions:
      - check-success=Code Check (ubuntu18.04)
      - check-success=Unit Test (ubuntu18.04)
      - check-success=System Integration Test (ubuntu18.04)
      - check-success=Test Deploy by Manifest (ubuntu18.04)
      - check-success=codecov/patch
      - check-success=codecov/project
      - label=lgtm
    actions:
      merge:
        method: merge
