apiVersion: batch/v1
kind: Job
metadata:
  name: checker
spec:
  ttlSecondsAfterFinished: 100
  template:
    spec:
      securityContext:
        runAsNonRoot: true
      serviceAccountName: checker
      restartPolicy: OnFailure
      containers:
      - name: checker
        image: milvusdb/milvus-operator:main-latest 
        command: ["/checker"]
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
          requests:
            cpu: 200m
            memory: 200Mi
        securityContext:
          allowPrivilegeEscalation: false