
---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-milvus-io-v1alpha1-milvus
  failurePolicy: Fail
  name: mmilvus.kb.io
  rules:
  - apiGroups:
    - milvus.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - milvuses
  sideEffects: None
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-milvus-io-v1alpha1-milvuscluster
  failurePolicy: Fail
  name: mmilvuscluster.kb.io
  rules:
  - apiGroups:
    - milvus.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - milvusclusters
  sideEffects: None

---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-milvus-io-v1alpha1-milvus
  failurePolicy: Fail
  name: vmilvus.kb.io
  rules:
  - apiGroups:
    - milvus.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - milvuses
  sideEffects: None
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-milvus-io-v1alpha1-milvuscluster
  failurePolicy: Fail
  name: vmilvuscluster.kb.io
  rules:
  - apiGroups:
    - milvus.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - milvusclusters
  sideEffects: None
