# permissions for end users to edit milvus.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: milvus-editor-role
rules:
- apiGroups:
  - milvus.io
  resources:
  - milvuses
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - milvus.io
  resources:
  - milvus/status
  verbs:
  - get
