# permissions for end users to view milvusclusters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: milvuscluster-viewer-role
rules:
- apiGroups:
  - milvus.io
  resources:
  - milvusclusters
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - milvus.io
  resources:
  - milvusclusters/status
  verbs:
  - get
