# permissions for end users to view milvus.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: milvus-viewer-role
rules:
- apiGroups:
  - milvus.io
  resources:
  - milvuses
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - milvus.io
  resources:
  - milvuses/status
  verbs:
  - get
