# permissions for end users to edit milvusclusters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: milvuscluster-editor-role
rules:
- apiGroups:
  - milvus.io
  resources:
  - milvusclusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - milvus.io
  resources:
  - milvusclusters/status
  verbs:
  - get
