# permissions for end users to edit milvusupgrades.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: milvusupgrade-editor-role
rules:
- apiGroups:
  - milvus.io
  resources:
  - milvusupgrades
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - milvus.io
  resources:
  - milvusupgrades/status
  verbs:
  - get
