# permissions for end users to view milvusupgrades.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: milvusupgrade-viewer-role
rules:
- apiGroups:
  - milvus.io
  resources:
  - milvusupgrades
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - milvus.io
  resources:
  - milvusupgrades/status
  verbs:
  - get
