apiVersion: milvus.io/v1alpha1
kind: MilvusCluster
metadata:
  name: my-release
  namespace: default
  labels:
    app: milvus
spec:
  dependencies: {}
  components: {}
  config:
    etcd:
      rootPath: my-release
    minio:
      bucketName: my-bucket