# This sample file is used to deploy Milvus with GCS as its object storage
# and access GCS with AssumeRole.

# change the <parameters> to match your environment
apiVersion: milvus.io/v1beta1
kind: Milvus
metadata:
  name: my-release
  labels:
    app: milvus
spec:
  components:
    serviceAccountName: my-release-sa
  config:
    minio:
      cloudProvider: gcp
      bucketName: <my-bucket-name>
      rootPath: milvus/my-release
      useSSL: true
      useIAM: true
  dependencies:
    etcd:
      inCluster:
        values:
          replicaCount: 1
        deletionPolicy: Delete
        pvcDeletion: true
    storage:
      external: true
      type: S3
      # Note: you must use regional endpoint here, otherwise the minio client that milvus uses will fail to connect
      endpoint: storage.googleapis.com:443
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: my-release-sa
  # gcp-service-account in the form of: <gcp-service-account-name>@<gcp-project-id>.iam.gserviceaccount.com
  iam.gke.io/gcp-service-account: <my-gcp-service-account>
