# This is a sample to configure a milvus's cpu and memory resources.

apiVersion: milvus.io/v1beta1
kind: Milvus
metadata:
  name: my-release
  labels:
    app: milvus
spec:
  components:
    resources:
      limits:
        cpu: '4'
        memory: 8Gi
      requests:
        cpu: '1'
        memory: 2Gi
  config: {}
  dependencies: {}