apiVersion: milvus.io/v1alpha1
kind: MilvusCluster
metadata:
  name: my-release
  labels:
    app: milvus
spec:
  dependencies: 
    etcd:
      inCluster:
        deletionPolicy: Delete
        persistenceKeep: false
    pulsar:
      inCluster:
        deletionPolicy: Delete
        persistenceKeep: false
    storage:
      inCluster:
        deletionPolicy: Delete
        persistenceKeep: false