# This is an example of Milvus deployment with Kafka as the message stream.
apiVersion: milvus.io/v1beta1
kind: Milvus
metadata:
  name: my-release
  labels:
    app: milvus
spec:
  dependencies:
    msgStreamType: kafka
    kafka:
      inCluster:
        deletionPolicy: Delete
        pvcDeletion: true

