# This sample file is used to deploy Milvus with GCS as its object storage.
# change the <parameters> to match your environment
apiVersion: milvus.io/v1beta1
kind: Milvus
metadata:
  name: my-release
  labels:
    app: milvus
spec:
  config:
    minio:
      cloudProvider: gcp
      bucketName: <my-bucket-name>
      rootPath: milvus/my-release
      useSSL: true
  dependencies:
    etcd:
      inCluster:
        values:
          replicaCount: 1
        deletionPolicy: Delete
        pvcDeletion: true
    storage:
      external: true
      type: S3
      endpoint: storage.googleapis.com:443
      secretRef: "my-release-s3-secret"
---
apiVersion: v1
kind: Secret
metadata:
  name: my-release-s3-secret
type: Opaque
stringData:
  accesskey: <my-access-key>
  secretkey: <my-secret-key>
