apiVersion: milvus.io/v1alpha1
kind: Milvus
metadata:
  name: my-release
  labels:
    app: milvus
spec:
  resources:
    limits:
      cpu: '4'
      memory: 8Gi
    requests:
      cpu: '1'
      memory: 2Gi
  serviceType: LoadBalancer
  config: {}
  dependencies: {}