apiVersion: milvus.io/v1beta1
kind: Milvus
metadata:
  name: my-release
  labels:
    app: milvus
spec:
  mode: cluster
  dependencies: {}
  components: 
    # mixCoord deploys all coordinators in one 'mixture' deployment
    mixCoord:
      replicas: 1
  config: {}