# change the <parameters> to match your environment
apiVersion: milvus.io/v1beta1
kind: Milvus
metadata:
  name: my-release
  labels:
    app: milvus
spec:
  components:
    serviceAccountName: my-release-sa
  config:
    minio:
      cloudProvider: gcp
      bucketName: <my-bucket-name>
      rootPath: milvus/my-release
      useSSL: true
      useIAM: true
  dependencies:
    etcd:
      inCluster:
        values:
          replicaCount: 1
        deletionPolicy: Delete
        pvcDeletion: true
    storage:
      external: true
      type: S3
      endpoint: storage.googleapis.com:443
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: my-release-sa
  eks.amazonaws.com/role-arn: <my-role-arn>
