apiVersion: milvus.io/v1alpha1
kind: MilvusCluster
metadata:
  name: my-release
  labels:
    app: milvus
spec:
  dependencies: {}
  components: {}
  config:
    milvus:
      etcd:
        rootPath: my-release
      minio:
        bucketName: my-bucket
