# This is a sample to configure a milvus cluster's cpu and memory resources.
apiVersion: milvus.io/v1beta1
kind: Milvus
metadata:
  name: my-release
  labels:
    app: milvus
spec:
  mode: cluster
  components:
    resources:
      limits:
        cpu: '4'
        memory: 8Gi
      requests:
        cpu: 200m
        memory: 512Mi
    dataCoord:
      replicas: 1
    dataNode:
      replicas: 1
    indexCoord:
      replicas: 1
    indexNode:
      replicas: 1
    proxy:
      replicas: 1
      serviceType: LoadBalancer
      resources:
        limits:
          cpu: '2'
          memory: 4Gi
        requests:
          cpu: 100m
          memory: 128Mi
    queryCoord:
      replicas: 1
    queryNode:
      replicas: 1
    rootCoord:
      replicas: 1
  config: {}
  dependencies: {}