// +build !ignore_autogenerated

/*
Copyright 2021.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/api/core/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Component) DeepCopyInto(out *Component) {
	*out = *in
	if in.Replicas != nil {
		in, out := &in.Replicas, &out.Replicas
		*out = new(int32)
		**out = **in
	}
	if in.GRPC != nil {
		in, out := &in.GRPC, &out.GRPC
		*out = new(ConfigGRPC)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Component.
func (in *Component) DeepCopy() *Component {
	if in == nil {
		return nil
	}
	out := new(Component)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfigGRPC) DeepCopyInto(out *ConfigGRPC) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfigGRPC.
func (in *ConfigGRPC) DeepCopy() *ConfigGRPC {
	if in == nil {
		return nil
	}
	out := new(ConfigGRPC)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Coordinator) DeepCopyInto(out *Coordinator) {
	*out = *in
	in.Component.DeepCopyInto(&out.Component)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Coordinator.
func (in *Coordinator) DeepCopy() *Coordinator {
	if in == nil {
		return nil
	}
	out := new(Coordinator)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DataCoordinator) DeepCopyInto(out *DataCoordinator) {
	*out = *in
	in.Coordinator.DeepCopyInto(&out.Coordinator)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DataCoordinator.
func (in *DataCoordinator) DeepCopy() *DataCoordinator {
	if in == nil {
		return nil
	}
	out := new(DataCoordinator)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DataNode) DeepCopyInto(out *DataNode) {
	*out = *in
	in.Node.DeepCopyInto(&out.Node)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DataNode.
func (in *DataNode) DeepCopy() *DataNode {
	if in == nil {
		return nil
	}
	out := new(DataNode)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IndexCoordinator) DeepCopyInto(out *IndexCoordinator) {
	*out = *in
	in.Coordinator.DeepCopyInto(&out.Coordinator)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IndexCoordinator.
func (in *IndexCoordinator) DeepCopy() *IndexCoordinator {
	if in == nil {
		return nil
	}
	out := new(IndexCoordinator)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IndexNode) DeepCopyInto(out *IndexNode) {
	*out = *in
	in.Node.DeepCopyInto(&out.Node)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IndexNode.
func (in *IndexNode) DeepCopy() *IndexNode {
	if in == nil {
		return nil
	}
	out := new(IndexNode)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MiluvsEtcd) DeepCopyInto(out *MiluvsEtcd) {
	*out = *in
	if in.Endpoints != nil {
		in, out := &in.Endpoints, &out.Endpoints
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.InClusterSpec != nil {
		in, out := &in.InClusterSpec, &out.InClusterSpec
		*out = new(MilvusEtcdSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MiluvsEtcd.
func (in *MiluvsEtcd) DeepCopy() *MiluvsEtcd {
	if in == nil {
		return nil
	}
	out := new(MiluvsEtcd)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MilvusCluster) DeepCopyInto(out *MilvusCluster) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MilvusCluster.
func (in *MilvusCluster) DeepCopy() *MilvusCluster {
	if in == nil {
		return nil
	}
	out := new(MilvusCluster)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MilvusCluster) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MilvusClusterCondition) DeepCopyInto(out *MilvusClusterCondition) {
	*out = *in
	if in.LastTransitionTime != nil {
		in, out := &in.LastTransitionTime, &out.LastTransitionTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MilvusClusterCondition.
func (in *MilvusClusterCondition) DeepCopy() *MilvusClusterCondition {
	if in == nil {
		return nil
	}
	out := new(MilvusClusterCondition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MilvusClusterList) DeepCopyInto(out *MilvusClusterList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]MilvusCluster, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MilvusClusterList.
func (in *MilvusClusterList) DeepCopy() *MilvusClusterList {
	if in == nil {
		return nil
	}
	out := new(MilvusClusterList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MilvusClusterList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MilvusClusterSpec) DeepCopyInto(out *MilvusClusterSpec) {
	*out = *in
	if in.ImagePullPolicy != nil {
		in, out := &in.ImagePullPolicy, &out.ImagePullPolicy
		*out = new(v1.PullPolicy)
		**out = **in
	}
	if in.ImagePullSecrets != nil {
		in, out := &in.ImagePullSecrets, &out.ImagePullSecrets
		*out = make([]v1.LocalObjectReference, len(*in))
		copy(*out, *in)
	}
	if in.Env != nil {
		in, out := &in.Env, &out.Env
		*out = make([]v1.EnvVar, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.EnvFrom != nil {
		in, out := &in.EnvFrom, &out.EnvFrom
		*out = make([]v1.EnvFromSource, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Etcd != nil {
		in, out := &in.Etcd, &out.Etcd
		*out = new(MiluvsEtcd)
		(*in).DeepCopyInto(*out)
	}
	if in.Storage != nil {
		in, out := &in.Storage, &out.Storage
		*out = new(MilvusStorage)
		**out = **in
	}
	if in.Pulsar != nil {
		in, out := &in.Pulsar, &out.Pulsar
		*out = new(MilvusPulsar)
		**out = **in
	}
	if in.Proxy != nil {
		in, out := &in.Proxy, &out.Proxy
		*out = new(Proxy)
		(*in).DeepCopyInto(*out)
	}
	if in.RootCoord != nil {
		in, out := &in.RootCoord, &out.RootCoord
		*out = new(RootCoordinator)
		(*in).DeepCopyInto(*out)
	}
	if in.DataCoord != nil {
		in, out := &in.DataCoord, &out.DataCoord
		*out = new(DataCoordinator)
		(*in).DeepCopyInto(*out)
	}
	if in.QueryCoord != nil {
		in, out := &in.QueryCoord, &out.QueryCoord
		*out = new(QueryCoordinator)
		(*in).DeepCopyInto(*out)
	}
	if in.IndexCoord != nil {
		in, out := &in.IndexCoord, &out.IndexCoord
		*out = new(IndexCoordinator)
		(*in).DeepCopyInto(*out)
	}
	if in.QueryNode != nil {
		in, out := &in.QueryNode, &out.QueryNode
		*out = new(QueryNode)
		(*in).DeepCopyInto(*out)
	}
	if in.DataNode != nil {
		in, out := &in.DataNode, &out.DataNode
		*out = new(DataNode)
		(*in).DeepCopyInto(*out)
	}
	if in.IndexNode != nil {
		in, out := &in.IndexNode, &out.IndexNode
		*out = new(IndexNode)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MilvusClusterSpec.
func (in *MilvusClusterSpec) DeepCopy() *MilvusClusterSpec {
	if in == nil {
		return nil
	}
	out := new(MilvusClusterSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MilvusClusterStatus) DeepCopyInto(out *MilvusClusterStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]MilvusClusterCondition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.EtcdStatus != nil {
		in, out := &in.EtcdStatus, &out.EtcdStatus
		*out = make([]MilvusEtcdStatus, len(*in))
		copy(*out, *in)
	}
	if in.StorageStatus != nil {
		in, out := &in.StorageStatus, &out.StorageStatus
		*out = make([]MilvusStorageStatus, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MilvusClusterStatus.
func (in *MilvusClusterStatus) DeepCopy() *MilvusClusterStatus {
	if in == nil {
		return nil
	}
	out := new(MilvusClusterStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MilvusEtcdSpec) DeepCopyInto(out *MilvusEtcdSpec) {
	*out = *in
	if in.Replicas != nil {
		in, out := &in.Replicas, &out.Replicas
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MilvusEtcdSpec.
func (in *MilvusEtcdSpec) DeepCopy() *MilvusEtcdSpec {
	if in == nil {
		return nil
	}
	out := new(MilvusEtcdSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MilvusEtcdStatus) DeepCopyInto(out *MilvusEtcdStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MilvusEtcdStatus.
func (in *MilvusEtcdStatus) DeepCopy() *MilvusEtcdStatus {
	if in == nil {
		return nil
	}
	out := new(MilvusEtcdStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MilvusPulsar) DeepCopyInto(out *MilvusPulsar) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MilvusPulsar.
func (in *MilvusPulsar) DeepCopy() *MilvusPulsar {
	if in == nil {
		return nil
	}
	out := new(MilvusPulsar)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MilvusStorage) DeepCopyInto(out *MilvusStorage) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MilvusStorage.
func (in *MilvusStorage) DeepCopy() *MilvusStorage {
	if in == nil {
		return nil
	}
	out := new(MilvusStorage)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MilvusStorageStatus) DeepCopyInto(out *MilvusStorageStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MilvusStorageStatus.
func (in *MilvusStorageStatus) DeepCopy() *MilvusStorageStatus {
	if in == nil {
		return nil
	}
	out := new(MilvusStorageStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Node) DeepCopyInto(out *Node) {
	*out = *in
	in.Component.DeepCopyInto(&out.Component)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Node.
func (in *Node) DeepCopy() *Node {
	if in == nil {
		return nil
	}
	out := new(Node)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Proxy) DeepCopyInto(out *Proxy) {
	*out = *in
	in.Node.DeepCopyInto(&out.Node)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Proxy.
func (in *Proxy) DeepCopy() *Proxy {
	if in == nil {
		return nil
	}
	out := new(Proxy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QueryCoordinator) DeepCopyInto(out *QueryCoordinator) {
	*out = *in
	in.Coordinator.DeepCopyInto(&out.Coordinator)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QueryCoordinator.
func (in *QueryCoordinator) DeepCopy() *QueryCoordinator {
	if in == nil {
		return nil
	}
	out := new(QueryCoordinator)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QueryNode) DeepCopyInto(out *QueryNode) {
	*out = *in
	in.Node.DeepCopyInto(&out.Node)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QueryNode.
func (in *QueryNode) DeepCopy() *QueryNode {
	if in == nil {
		return nil
	}
	out := new(QueryNode)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RootCoordinator) DeepCopyInto(out *RootCoordinator) {
	*out = *in
	in.Coordinator.DeepCopyInto(&out.Coordinator)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RootCoordinator.
func (in *RootCoordinator) DeepCopy() *RootCoordinator {
	if in == nil {
		return nil
	}
	out := new(RootCoordinator)
	in.DeepCopyInto(out)
	return out
}
