/*
Copyright 2021.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/milvus-io/milvus-operator/apis/milvus.io/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeMilvusClusters implements MilvusClusterInterface
type FakeMilvusClusters struct {
	Fake *FakeMilvusV1alpha1
	ns   string
}

var milvusclustersResource = schema.GroupVersionResource{Group: "milvus.io", Version: "v1alpha1", Resource: "milvusclusters"}

var milvusclustersKind = schema.GroupVersionKind{Group: "milvus.io", Version: "v1alpha1", Kind: "MilvusCluster"}

// Get takes name of the milvusCluster, and returns the corresponding milvusCluster object, and an error if there is any.
func (c *FakeMilvusClusters) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.MilvusCluster, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(milvusclustersResource, c.ns, name), &v1alpha1.MilvusCluster{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.MilvusCluster), err
}

// List takes label and field selectors, and returns the list of MilvusClusters that match those selectors.
func (c *FakeMilvusClusters) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.MilvusClusterList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(milvusclustersResource, milvusclustersKind, c.ns, opts), &v1alpha1.MilvusClusterList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.MilvusClusterList{ListMeta: obj.(*v1alpha1.MilvusClusterList).ListMeta}
	for _, item := range obj.(*v1alpha1.MilvusClusterList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested milvusClusters.
func (c *FakeMilvusClusters) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(milvusclustersResource, c.ns, opts))

}

// Create takes the representation of a milvusCluster and creates it.  Returns the server's representation of the milvusCluster, and an error, if there is any.
func (c *FakeMilvusClusters) Create(ctx context.Context, milvusCluster *v1alpha1.MilvusCluster, opts v1.CreateOptions) (result *v1alpha1.MilvusCluster, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(milvusclustersResource, c.ns, milvusCluster), &v1alpha1.MilvusCluster{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.MilvusCluster), err
}

// Update takes the representation of a milvusCluster and updates it. Returns the server's representation of the milvusCluster, and an error, if there is any.
func (c *FakeMilvusClusters) Update(ctx context.Context, milvusCluster *v1alpha1.MilvusCluster, opts v1.UpdateOptions) (result *v1alpha1.MilvusCluster, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(milvusclustersResource, c.ns, milvusCluster), &v1alpha1.MilvusCluster{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.MilvusCluster), err
}

// Delete takes name of the milvusCluster and deletes it. Returns an error if one occurs.
func (c *FakeMilvusClusters) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(milvusclustersResource, c.ns, name), &v1alpha1.MilvusCluster{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeMilvusClusters) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(milvusclustersResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.MilvusClusterList{})
	return err
}

// Patch applies the patch and returns the patched milvusCluster.
func (c *FakeMilvusClusters) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.MilvusCluster, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(milvusclustersResource, c.ns, name, pt, data, subresources...), &v1alpha1.MilvusCluster{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.MilvusCluster), err
}
