namePrefix: '{{ include "chart.fullname" . }}-'

namespace: '{{ .Release.Namespace }}'

generatorOptions:
  disableNameSuffixHash: true

commonAnnotations:
  cert-manager.io/inject-ca-from: '{{.Release.Namespace}}/{{. | include "chart.fullname"}}-serving-cert'

patchesStrategicMerge:
- webhook_patch.yaml

bases:
- ../../crd
