# The following patch enables a conversion webhook for the CRD
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: milvuses.milvus.io
spec:
  conversion:
    strategy: Webhook
    webhook:
      clientConfig:
        service:
          namespace: '{{.Release.Namespace}}'
          name: '{{. | include "chart.fullname"}}-webhook-service'
          path: /convert
      conversionReviewVersions:
      - v1
