{{- if .Values.apiIngress.enabled -}}
apiVersion: {{ include "common.capabilities.ingress.apiVersion" . }}
kind: Ingress
metadata:
  name: {{ include "common.names.fullname" . }}-api
  namespace: {{ .Release.Namespace }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  annotations:
    {{- if .Values.apiIngress.certManager }}
    kubernetes.io/tls-acme: "true"
    {{- end }}
    {{- if .Values.apiIngress.annotations }}
    {{- include "common.tplvalues.render" (dict "value" .Values.apiIngress.annotations "context" $) | nindent 4 }}
    {{- end }}
    {{- if .Values.commonAnnotations }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
    {{- end }}
spec:
  rules:
    {{- if .Values.apiIngress.hostname }}
    - host: {{ .Values.apiIngress.hostname }}
      http:
        paths:
          {{- if .Values.apiIngress.extraPaths }}
          {{- toYaml .Values.apiIngress.extraPaths | nindent 10 }}
          {{- end }}
          - path: {{ .Values.apiIngress.path }}
            {{- if eq "true" (include "common.ingress.supportsPathType" .) }}
            pathType: {{ .Values.apiIngress.pathType }}
            {{- end }}
            backend: {{- include "common.ingress.backend" (dict "serviceName" (include "common.names.fullname" .) "servicePort" "minio-api" "context" $)  | nindent 14 }}
    {{- end }}
    {{- range .Values.apiIngress.extraHosts }}
    - host: {{ .name | quote }}
      http:
        paths:
          - path: {{ default "/" .path }}
            {{- if eq "true" (include "common.ingress.supportsPathType" $) }}
            pathType: {{ default "ImplementationSpecific" .pathType }}
            {{- end }}
            backend: {{- include "common.ingress.backend" (dict "serviceName" (include "common.names.fullname" $) "servicePort" "minio-api" "context" $) | nindent 14 }}
    {{- end }}
  {{- if or .Values.apiIngress.tls .Values.apiIngress.extraTls }}
  tls:
    {{- if .Values.apiIngress.tls }}
    - hosts:
        - {{ .Values.apiIngress.hostname }}
      secretName: {{ printf "%s-tls" .Values.apiIngress.hostname }}
    {{- end }}
    {{- if .Values.apiIngress.extraTls }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.apiIngress.extraTls "context" $ ) | nindent 4 }}
    {{- end }}
  {{- end }}
{{- end }}
