apiVersion: v1
kind: Service
metadata:
  labels:
    service-kind: metrics
    {{- include "chart.labels" . | nindent 4 }}
  name: '{{ include "chart.fullname" . }}-metrics-service'
  namespace: {{ .Release.Namespace | quote }}
spec:
  ports:
  - name: metrics
    port: 8443
    targetPort: metrics
  selector: 
    {{- include "chart.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "chart.labels" . | nindent 4 }}
  name: '{{ include "chart.fullname" . }}-webhook-service'
  namespace: {{ .Release.Namespace | quote }}
spec:
  ports:
  - port: 443
    targetPort: webhook-server
    protocol: TCP
    name: https
  selector:
    {{- include "chart.selectorLabels" . | nindent 4 }}
