name: Test Deploy With Minifest

# This workflow is triggered on any golang code, makefile, workflow changes to repository.
on:
  push:
    paths-ignore:
      - 'docs/**'
  pull_request:
    paths-ignore:
      - 'docs/**'

jobs:
  deploy-by-manifest:
    name: Test Deploy by Manifest
    runs-on: ubuntu-latest
    timeout-minutes: 40
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu18.04]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup KinD Cluster
        uses: engineerd/setup-kind@v0.5.0
        with:
          version: "v0.11.1"
      - name: Deploy by manifest
        run: |
          make deploy-by-manifest
      - name: Test Webhook
        run : |
          set -ex
          kubectl create -f ./config/samples/milvus_minimum.yaml
          kubectl delete -f ./config/samples/milvus_minimum.yaml
          kubectl create -f ./config/samples/milvus_cluster_minimum.yaml
          kubectl delete -f ./config/samples/milvus_cluster_minimum.yaml
