name: Build and Push Latest on Main

# This workflow is triggered on new pushed to the main branch.
on:
  push:
    branches:
      - main

jobs:
  publish-builder:
    name: Publish Builder
    runs-on: ubuntu-latest
    timeout-minutes: 15
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu18.04]
    env:
      OS_NAME: ${{ matrix.os }}
      REGISTRY_NAME: milvusdb/milvus-operator
      IMAGE_TAG: "main-latest"
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build Docker Image
        shell: bash
        run: |
          docker build -t ${REGISTRY_NAME}:${IMAGE_TAG} .
      - name: Push Docker Image
        shell: bash
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} \
                       -p ${{ secrets.DOCKER_PWD }}
          docker push ${REGISTRY_NAME}:${IMAGE_TAG}
